# Generated by Django 3.2.25 on 2025-12-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
    ]
